<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class FlowInfo extends Model
{
    //
    protected $table = 'flow_info';

    protected $primaryKey = 'flow_id';

    protected $fillable = ['activity_key', 'flow_name', 'type',
        'location', 'sms_temp_id', 'score', 'evaluation', 'correlation', 'lock', 'time_description',
        'start_time', 'end_time'];

    public function getFlowInfo($condition, $need)
    {
        return $this->where('status', '>=', 0)->where($condition)->select($need)->first();
    }

    public function getFlowList($condition, $need)
    {
        return $this->where('status', '>=', 0)
            ->where($condition)
            ->select($need)
            ->orderBy('created_at', 'asc')
            ->get();
    }

    public function storeNewFlow($data)
    {
        return $this->create($data);
    }

    public function updateFlowInfo($condition, $data)
    {
        return $this->where($condition)->update($data);
    }

    public function belongsToAct()
    {
        return parent::belongsTo('App\Models\Activity_design', 'activity_key', 'activity_id'); // TODO: Change the autogenerated stub
    }

}
